title: ElastiSim

permalink: pretty

remote_theme: just-the-docs/just-the-docs

logo: "/assets/logos/ElastiSim.svg"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

mermaid:
  version: "10.3.0"

aux_links:
  "ElastiSim on GitHub":
    - "//github.com/elastisim"

footer_content: "Copyright &copy; 2023, Technical University of Darmstadt."